name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install Dependencies
        run: ls -al && bun install

      - name: Typecheck
        run: bun run typecheck

      - name: Lint
        run: bun run lint
